### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by SylvainDe** [1cg/Lazy-Gosu#4]
I tried to visit http://www.lazygosu.org/ but it didn't seem to work.
Then I googled and found your github project and the URL https://lazy.github.com/ which doesn't work either.
I don't know if this project is still alive but as Gosu is currently on reddit.org/r/programming's front page, there might be other people trying to access ressources related to Gosu.

**Comment by 1cg** [comment]
Hi there, sorry for the delay on this.  I'm going to resurrect this site at lazy-gosu.github.io
